# Generated by Django 5.2 on 2025-05-26 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_members_alter_projectmember_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文档名称')),
                ('file', models.FileField(upload_to='project_documents/', verbose_name='文档文件')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='文档描述')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('analysis', models.TextField(blank=True, null=True, verbose_name='AI分析')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='project.project', verbose_name='所属项目')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
        ),
    ]
