# Generated by Django 5.2 on 2025-05-21 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('color', models.CharField(default='#409EFF', max_length=20, verbose_name='分类颜色')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文档分类',
                'verbose_name_plural': '文档分类',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文档标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='文档内容')),
                ('doc_type', models.CharField(default='通用', max_length=50, verbose_name='文档类型')),
                ('is_shared', models.BooleanField(default=False, verbose_name='是否共享')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_documents', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑者')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_documents', to=settings.AUTH_USER_MODEL, verbose_name='共享用户')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='smartdoc.documentcategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '智能文档',
                'verbose_name_plural': '智能文档',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(default='相关', max_length=50, verbose_name='关联类型')),
                ('relevance_score', models.FloatField(default=0.0, verbose_name='相关度分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('related_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='smartdoc.document', verbose_name='相关文档')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_documents', to='smartdoc.document', verbose_name='源文档')),
            ],
            options={
                'verbose_name': '相关文档',
                'verbose_name_plural': '相关文档',
                'ordering': ['-relevance_score'],
                'unique_together': {('source_document', 'related_document')},
            },
        ),
    ]
