# Generated by Django 4.2.10 on 2025-06-27 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartdoc', '0002_documentcategory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSharePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', '只读'), ('edit', '编辑')], default='read', max_length=10, verbose_name='权限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='smartdoc.document', verbose_name='文档')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文档共享权限',
                'verbose_name_plural': '文档共享权限',
                'ordering': ['-created_at'],
                'unique_together': {('document', 'user')},
            },
        ),
    ]
