# Generated by Django 4.2.10 on 2025-06-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_document_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='source',
            field=models.CharField(blank=True, help_text='Source of the message, e.g., knowledge_base or general_ai', max_length=20, null=True),
        ),
    ]
