# Generated by Django 4.2.10 on 2025-06-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aichatmessage_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='标记消息是否被删除'),
        ),
        migrations.AlterField(
            model_name='aichatmessage',
            name='source',
            field=models.CharField(blank=True, help_text="消息来源，如'knowledge_base', 'general_ai'等", max_length=50, null=True),
        ),
    ]
