# Generated by Django 4.2.10 on 2025-06-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aichatmessage_is_deleted_alter_aichatmessage_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='metadata',
            field=models.JSONField(blank=True, help_text='存储与消息相关的元数据，如文档ID', null=True),
        ),
    ]
