# Generated by Django 5.2 on 2025-05-08 09:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('start', models.DateTimeField(verbose_name='开始时间')),
                ('end', models.DateTimeField(verbose_name='结束时间')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='地点')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('type', models.CharField(choices=[('blue', '会议'), ('orange', '出差'), ('green', '假期'), ('red', '截止日期'), ('purple', '其他')], default='blue', max_length=20, verbose_name='事件类型')),
                ('reminder', models.CharField(choices=[('none', '不提醒'), ('10min', '10分钟前'), ('30min', '30分钟前'), ('1hour', '1小时前'), ('1day', '1天前')], default='30min', max_length=20, verbose_name='提醒时间')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='是否全天事件')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='参与者')),
            ],
            options={
                'verbose_name': '日历事件',
                'verbose_name_plural': '日历事件列表',
                'ordering': ['start'],
            },
        ),
    ]
