# Generated by Django 5.2 on 2025-05-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='is_all_day',
        ),
    ]
