# Generated by Django 5.2 on 2025-05-20 07:32

import apps.contract.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='合同编号')),
                ('title', models.CharField(max_length=200, verbose_name='合同标题')),
                ('type', models.CharField(max_length=50, verbose_name='合同类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='合同金额')),
                ('company', models.CharField(max_length=200, verbose_name='签约对方')),
                ('sign_date', models.DateField(blank=True, null=True, verbose_name='签约日期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('signed', '已签署'), ('expired', '已过期'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='合同状态')),
                ('content', models.TextField(blank=True, verbose_name='合同内容')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='操作类型')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='contract.contract', verbose_name='关联合同')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '合同操作记录',
                'verbose_name_plural': '合同操作记录列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='附件名称')),
                ('file', models.FileField(upload_to=apps.contract.models.contract_file_path, verbose_name='附件文件')),
                ('file_type', models.CharField(blank=True, max_length=20, verbose_name='文件类型')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='文件大小(KB)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contract.contract', verbose_name='关联合同')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '合同附件',
                'verbose_name_plural': '合同附件列表',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('contract_type', models.CharField(max_length=50, verbose_name='合同类型')),
                ('industry', models.CharField(blank=True, max_length=50, verbose_name='行业领域')),
                ('scene', models.CharField(blank=True, max_length=50, verbose_name='交易场景')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '合同模板',
                'verbose_name_plural': '合同模板列表',
                'ordering': ['contract_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contract.contracttemplate', verbose_name='使用的模板'),
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('content', models.TextField(verbose_name='合同内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contract.contract', verbose_name='关联合同')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '合同版本',
                'verbose_name_plural': '合同版本列表',
                'ordering': ['-version'],
                'unique_together': {('contract', 'version')},
            },
        ),
    ]
