# Generated by Django 5.2 on 2025-05-15 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('knowledge', '0001_initial'),  # 添加对knowledge应用的依赖
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_chats', to='knowledge.knowledgebase'),
        ),
    ]
