# Generated by Django 5.2 on 2025-05-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='calendar_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Calendar Data'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('knowledge', 'Knowledge'), ('calendar', 'Calendar')], default='text', max_length=10, verbose_name='Message Type'),
        ),
    ]
