# Generated by Django 5.2 on 2025-05-19 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UIPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', '浅色'), ('dark', '深色')], default='light', max_length=10, verbose_name='主题模式')),
                ('content_density', models.CharField(choices=[('compact', '紧凑'), ('normal', '标准'), ('comfortable', '宽松')], default='normal', max_length=15, verbose_name='内容密度')),
                ('font_size', models.IntegerField(default=14, verbose_name='字体大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_preference', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '界面偏好',
                'verbose_name_plural': '界面偏好',
            },
        ),
    ]
