# Generated by Django 5.2 on 2025-05-19 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='AI称呼用户')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户职业')),
                ('traits_text', models.TextField(blank=True, null=True, verbose_name='AI特征')),
                ('other_info', models.TextField(blank=True, null=True, verbose_name='其他信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_setting', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI个性化设置',
                'verbose_name_plural': 'AI个性化设置',
            },
        ),
    ]
