# Generated by Django 4.2.10 on 2025-06-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_aisetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisetting',
            name='tone',
            field=models.CharField(default='professional', max_length=20, verbose_name='沟通风格'),
        ),
    ]
